import { createElement } from "react";
import type { LucideIcon, LucideProps } from "lucide-react";
import {
  AppWindow,
  BarChart3,
  Bell,
  Blocks,
  Bot,
  BrainCircuit,
  Building2,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  CodeXml,
  Component,
  CreditCard,
  Database,
  Expand,
  FileCheck2,
  FileLock2,
  FileSearch,
  FileText,
  FlaskConical,
  Gauge,
  GitBranch,
  GitPullRequest,
  Globe,
  Handshake,
  Headset,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  MapPin,
  MessageCircle,
  MessagesSquare,
  PackageCheck,
  Palette,
  PanelsTopLeft,
  Plug,
  Puzzle,
  RefreshCw,
  Rocket,
  ScanText,
  Search,
  Server,
  ServerCog,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  SquareKanban,
  Store,
  TrendingUp,
  UserCheck,
  Users,
  UserSearch,
  UsersRound,
  Video,
  Webhook,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

// JSON content refers to icons by these keys.
const ICONS: Record<string, LucideIcon> = {
  appWindow: AppWindow,
  barChart: BarChart3,
  bell: Bell,
  blocks: Blocks,
  bot: Bot,
  brain: BrainCircuit,
  building: Building2,
  clipboardList: ClipboardList,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  codeXml: CodeXml,
  component: Component,
  creditCard: CreditCard,
  database: Database,
  expand: Expand,
  fileCheck: FileCheck2,
  fileLock: FileLock2,
  fileSearch: FileSearch,
  fileText: FileText,
  flask: FlaskConical,
  gauge: Gauge,
  gitBranch: GitBranch,
  gitPullRequest: GitPullRequest,
  globe: Globe,
  handshake: Handshake,
  headset: Headset,
  kanban: SquareKanban,
  keyRound: KeyRound,
  layers: Layers,
  layoutDashboard: LayoutDashboard,
  layoutGrid: LayoutGrid,
  mapPin: MapPin,
  messageCircle: MessageCircle,
  messagesSquare: MessagesSquare,
  packageCheck: PackageCheck,
  palette: Palette,
  panels: PanelsTopLeft,
  plug: Plug,
  puzzle: Puzzle,
  refresh: RefreshCw,
  rocket: Rocket,
  scanText: ScanText,
  search: Search,
  server: Server,
  serverCog: ServerCog,
  shieldCheck: ShieldCheck,
  shoppingCart: ShoppingCart,
  smartphone: Smartphone,
  sparkles: Sparkles,
  store: Store,
  trendingUp: TrendingUp,
  userCheck: UserCheck,
  users: Users,
  userSearch: UserSearch,
  usersRound: UsersRound,
  video: Video,
  webhook: Webhook,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
};

export function getIcon(key: string | undefined): LucideIcon {
  return (key && ICONS[key]) || Sparkles;
}

// Renders an icon by key. Use this where the icon is chosen at render time
// outside a list, so no component is created during render.
export function DynamicIcon({ name, ...props }: { name?: string } & LucideProps) {
  return createElement(getIcon(name), props);
}
