import type { Section } from "../home-sections";

const sections: Section[] = [
  {
    id: "hero",
    label: "Hero",
    description: "The big title block at the very top of the page.",
    ready: true,
    fields: [
      { name: "badge", label: "Badge", type: "text", default: "Volume 01: The Journey" },
      { name: "headingLead", label: "Heading — line 1", type: "text", default: "The Story of" },
      { name: "headingHighlight", label: "Heading — line 2 (highlighted)", type: "text", default: "Fillip Technologies" },
      { name: "subheadline", label: "Sub-headline", type: "textarea", default: "Explore the milestones, minds, and methodologies that built our agency from a three-person workspace into a powerhouse of digital transformation." },
      { name: "image", label: "Side illustration", type: "image", default: "/images/our-story-neww.png", help: "Decorative image shown on the right of the hero (desktop only)." },
    ],
  },
  {
    id: "stats",
    label: "Stats bar",
    description: "The row of metric figures shown below the hero (add/remove as many as you like).",
    ready: true,
    fields: [],
    list: {
      name: "stats",
      label: "Stats",
      itemNoun: "stat",
      itemFields: [
        { name: "value", label: "Value", type: "text" },
        { name: "label", label: "Label", type: "text" },
      ],
      default: [
        { value: "13+", label: "Years of Innovation" },
        { value: "1500+", label: "Projects Delivered" },
        { value: "50+", label: "Team Experts" },
        { value: "98%", label: "Client Satisfaction" },
      ],
    },
  },
  {
    id: "timeline",
    label: "Story timeline",
    description: "Your year-by-year story — one entry per chapter/year. Icons and colours are set automatically.",
    ready: true,
    fields: [],
    list: {
      name: "chapters",
      label: "Chapters",
      itemNoun: "chapter",
      itemFields: [
        { name: "year", label: "Year", type: "text" },
        { name: "title", label: "Title", type: "text" },
        { name: "story", label: "Story", type: "textarea" },
        { name: "quote", label: "Quote", type: "textarea" },
        { name: "image", label: "Photo", type: "image" },
        { name: "stat1Label", label: "Highlight 1 — label", type: "text" },
        { name: "stat1Value", label: "Highlight 1 — value", type: "text" },
        { name: "stat2Label", label: "Highlight 2 — label", type: "text" },
        { name: "stat2Value", label: "Highlight 2 — value", type: "text" },
        { name: "stat3Label", label: "Highlight 3 — label", type: "text" },
        { name: "stat3Value", label: "Highlight 3 — value", type: "text" },
      ],
      default: [
        { year: "2018", title: "The Seed is Sown", story: "illip Technologies starts in a small incubation space with a core team of three digital visionaries and a goal to bridge the tech-marketing divide. We set up our first workflow systems and focused on building custom, client-centric web platforms.", quote: "We didn't have funding or fancy desks. We just had a vision that code and marketing must act as one.", image: "/images/saas-desk-setup.png", stat1Label: "Core Team", stat1Value: "3 Experts", stat2Label: "Primary Tech", stat2Value: "HTML5, PHP, CSS", stat3Label: "Projects", stat3Value: "12 Completed" },
        { year: "2020", title: "Transition to Digital", story: "s the world transitions, we support brick-and-mortar brands in shifting to robust e-commerce and secure, remote workflows. We designed custom payment integrations and secured databases to help companies withstand global disruption.", quote: "Disruption forced the world to adapt. We stood beside our clients to build resilience, remote systems, and e-commerce.", image: "/images/How-we-work.png", stat1Label: "Core Team", stat1Value: "15 Experts", stat2Label: "Primary Tech", stat2Value: "React, Node, PostgreSQL", stat3Label: "Projects", stat3Value: "45 Completed" },
        { year: "2022", title: "Growth & Scaling", story: "e expand our expertise to custom software development and advanced branding, growing our team to 40+ professionals and moving to a larger headquarters. We established rigorous automation standards to match the expectations of larger enterprise partners.", quote: "Growth is not just about size. It is about standardizing excellence, automating pipelines, and moving to our main office.", image: "/images/capabilities-background.png", stat1Label: "Core Team", stat1Value: "40+ Experts", stat2Label: "Primary Tech", stat2Value: "Next.js, Tailwind, NestJS", stat3Label: "Projects", stat3Value: "95+ Completed" },
        { year: "2024", title: "Global Operations", story: "stablishing partnerships with global brands across 5+ countries, establishing our presence in international digital consulting. We redesigned workflows, built scalable portals, and proved that a client-first agency can deliver elite code worldwide.", quote: "Borders are constructs. True engineering talent speaks a universal language of quality and speed.", image: "/images/research-mockup.png", stat1Label: "Core Team", stat1Value: "50+ Experts", stat2Label: "Primary Tech", stat2Value: "AWS, GCP, GraphQL, Python", stat3Label: "Projects", stat3Value: "140+ Completed" },
        { year: "2026 & Beyond", title: "Next Gen AI & SaaS", story: "ushing boundaries with custom AI integrations, chatbot agents, and automated SaaS products to lead the next generation of tech. We believe AI will define modern product scaling, and we are already delivering the pipelines that make it happen.", quote: "AI will not replace strategy; it will amplify it. We are building the automated pipelines of tomorrow, today.", image: "/images/saas-dashboard.png", stat1Label: "Core Team", stat1Value: "55+ Experts", stat2Label: "Primary Tech", stat2Value: "LangChain, OpenAI API, SaaS", stat3Label: "Projects", stat3Value: "150+ Completed" },
      ],
    },
  },
  {
    id: "missionvision",
    label: "Mission, Vision & Team",
    description: "The bottom band of the page: your mission/vision/values, the founder (CEO) block, the team grid and the closing sign-off.",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Small label above heading", type: "text", default: "AFTERWORD", group: "Section header", help: "Tiny label shown above the main heading." },
      { name: "heading", label: "Main heading", type: "text", default: "Pioneering the Agentic Future", group: "Section header" },
      { name: "missionText", label: "Our Mission", type: "textarea", default: "To empower modern brands with high-performance custom engineering, future-proof agentic AI systems, and search optimization, transforming complex operational workflows and marketing budgets into measurable business growth.", group: "Mission, Vision & Values" },
      { name: "visionText", label: "Our Vision", type: "textarea", default: "To establish ourselves as a global benchmark for digital execution and next-generation agentic AI, proving that client transparency, clean scalable code, and forward-looking automation can consistently win on the international stage.", group: "Mission, Vision & Values" },
      { name: "creedText", label: "Our Values", type: "textarea", default: "We make commitments, not excuses. We work with absolute accountability, leverage AI responsibly to amplify human intelligence, refuse code shortcuts, and measure our agency's reputation directly by the scalability and success of the products we launch.", group: "Mission, Vision & Values", help: "Shown as the third column (was labelled \"Creed\")." },
      { name: "leadershipEyebrow", label: "Small label above heading", type: "text", default: "Leadership & Team", group: "Leadership & team heading" },
      { name: "leadershipHeading", label: "Heading", type: "text", default: "The People Behind The Pages", group: "Leadership & team heading" },
      { name: "leadershipDescription", label: "Intro text", type: "textarea", default: "One clear leadership voice, supported by a focused team of builders, designers, and growth specialists.", group: "Leadership & team heading" },
      { name: "ceoName", label: "Name", type: "text", default: "Vikash Kumar", group: "Founder / CEO" },
      { name: "ceoRole", label: "Role / title", type: "text", default: "Founder & CEO", group: "Founder / CEO" },
      { name: "ceoExperience", label: "Experience line", type: "text", default: "13+ Years of Experience", group: "Founder / CEO" },
      { name: "ceoImage", label: "Photo", type: "image", default: "/images/team/VIKASH.jpeg", group: "Founder / CEO" },
      { name: "ceoMessage", label: "Message / quote", type: "textarea", default: "Fillip Technologies was built with a simple belief: technology should make businesses clearer, faster, and more capable. Every solution we deliver carries our promise of discipline, transparency, and meaningful digital impact for the businesses we serve.", group: "Founder / CEO" },
      { name: "signatureLead", label: "Sign-off line", type: "text", default: "Signed in code and character,", group: "Closing signature" },
      { name: "signatureName", label: "Signed by", type: "text", default: "The Fillip Team", group: "Closing signature" },
    ],
    list: {
      name: "teamMembers",
      label: "Team members",
      itemNoun: "member",
      itemFields: [
        { name: "name", label: "Name", type: "text" },
        { name: "role", label: "Role", type: "text" },
        { name: "image", label: "Photo", type: "image" },
        { name: "imagePosition", label: "Photo focus (e.g. object-[50%_18%])", type: "text" },
      ],
      default: [
        { name: "Risabh Choubey", role: "Account Manager", image: "", imagePosition: "" },
        { name: "Shruti Sinha", role: "IT Team Lead", image: "/images/team/shruti-sinha.jpeg", imagePosition: "" },
        { name: "Payal Kumari", role: "Digital Marketing Head", image: "/images/team/Payal.jpeg", imagePosition: "" },
        { name: "Shruti Chouhan", role: "Software Development Engineer II", image: "/images/team/shruti-singh.png", imagePosition: "" },
        { name: "Abhishek Prajapati", role: "Backend Developer", image: "/images/team/ABHISHEK.jpeg", imagePosition: "" },
        { name: "Prince Raj", role: "Associate Software Developer", image: "/images/team/prince-kumar.png", imagePosition: "object-[50%_18%]" },
        { name: "Govind Kumar", role: "Associate Software Developer", image: "/images/team/Govind-Kumar.png", imagePosition: "object-[50%_18%]" },
        { name: "Aman Sharma", role: "Digital Marketing Executive", image: "", imagePosition: "" },
        { name: "Mukta Trivedy", role: "UI Designer", image: "/images/team/mukta-trivedy.png", imagePosition: "" },
        { name: "Wagish Karna", role: "Content Writer", image: "/images/team/wagish-karna.jpeg", imagePosition: "object-[50%_18%]" },
        { name: "Khushi Bharti", role: "HR Generalist", image: "", imagePosition: "" },
        { name: "Lincy Bhardwaj", role: "HR Executive", image: "", imagePosition: "" },
        { name: "Anushka Raj", role: "BDE", image: "", imagePosition: "" },
      ],
    },
  },
];

export const ourStoryGroup = { id: "our-story", label: "Our Story", description: "The /our-story page.", sections };
