import type { Section } from "../home-sections";

const sections: Section[] = [
  {
    id: "hero",
    label: "Hero",
    description: "Heading + intro above the fanned project cards. The cards are editable below.",
    ready: true,
    fields: [
      { name: "headingLead", label: "Heading — line 1", type: "text", default: "Ideas shaped into" },
      { name: "headingHighlight", label: "Heading — line 2 (highlighted)", type: "text", default: "digital experiences." },
      { name: "description", label: "Description", type: "textarea", default: "Explore digital products, platforms and growth experiences built by Fillip Technologies for ambitious businesses and public institutions." },
    ],
    list: {
      name: "projects",
      label: "Project cards",
      itemNoun: "project",
      itemFields: [
        { name: "image", label: "Image", type: "image" },
        { name: "title", label: "Title", type: "text" },
        { name: "category", label: "Category", type: "text" },
      ],
      default: [
        { image: "/images/portfolio/litera-mockup.png", title: "Litera Valley School", category: "Education Industry" },
        { image: "/images/portfolio/sita-mockup.png", title: "Sita Interior", category: "Architecture Industry" },
        { image: "/images/portfolio/domus-mockup.png", title: "Domus Cure", category: "HealthCare Industry" },
        { image: "/images/portfolio/abhijeet-mockup.png", title: "Dr Abhijeet Jha", category: "Dermatology" },
        { image: "/images/portfolio/chaapak-mockup.png", title: "Chappak Resort", category: "Event Planning" },
        { image: "/images/portfolio/wedding-mockups.png", title: "Weddings72", category: "Event Planning" },
        { image: "/images/portfolio/technosys-mockup.png", title: "Technosys It and Managment", category: "It Industry" },
        { image: "/images/web-img.png", title: "Patna Zoo", category: "Government Industry" },
      ],
    },
  },
  {
    id: "showcase",
    label: "Client logos",
    description: "The grid of client & government logos. Add, remove or replace any logo.",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "✦ Selected Case Studies" },
      { name: "heading", label: "Heading", type: "text", default: "Our Portfolio" },
    ],
    list: {
      name: "logos",
      label: "Logos",
      itemNoun: "logo",
      itemFields: [
        { name: "name", label: "Name", type: "text" },
        { name: "image", label: "Logo", type: "image" },
      ],
      default: [
        { name: "Rajgir Zoo Safari", image: "/images/goverment/Zoo%20Safari%20logo%20copy.jpg" },
        { name: "Patna Park", image: "/images/goverment/Patna%20Park.png" },
        { name: "Patna Zoo", image: "/images/goverment/logo-large-converted-from-svg.png" },
        { name: "Vana Vani", image: "/images/NEW%20CLIENTS%20LOGO/Green%20and%20Beige%20Groceries%20Business%20Logo.png" },
        { name: "Nagar Parishad Jamui", image: "/images/NEW%20CLIENTS%20LOGO/jamui%20logo.png" },
        { name: "Thakurganj Nagar Panchayat", image: "/images/NEW%20CLIENTS%20LOGO/THAKUR%20GANJ%20NAGAR%20PANCHAYAT.png" },
        { name: "Domus Cure", image: "/images/NEW%20CLIENTS%20LOGO/Domus-logo%20png.png" },
        { name: "Gayatri Astroscience", image: "/images/NEW%20CLIENTS%20LOGO/logo%20(2).png" },
        { name: "Diagno First Lab", image: "/images/NEW%20CLIENTS%20LOGO/Diagno-lab-PNG.png" },
        { name: "Golden Apple", image: "/images/NEW%20CLIENTS%20LOGO/golden%20apple%20logo.png" },
        { name: "Inception", image: "/images/NEW%20CLIENTS%20LOGO/Inception%20logo.png" },
        { name: "Janya Hospital", image: "/images/NEW%20CLIENTS%20LOGO/Janya-Hospital-Logo-PNG%20copy.png" },
        { name: "Landmark Hotel", image: "/images/NEW%20CLIENTS%20LOGO/LANDMARK%20LOGO.png" },
        { name: "Ruban Hospital", image: "/images/NEW%20CLIENTS%20LOGO/Ruban%40logo-with-NABH-2-ovg23ovg0xx8ocfhzbaqtv86rfyyms5d4as9irornm.png" },
        { name: "Advante", image: "/images/NEW%20CLIENTS%20LOGO/Advante%20Logo%20Final%20-%2025-07-2022%20-%20Copy.png" },
        { name: "AHL", image: "/images/NEW%20CLIENTS%20LOGO/Ahl-logo-copy-300x76.png" },
        { name: "ARCS", image: "/images/NEW%20CLIENTS%20LOGO/ARCS.png" },
        { name: "BCIT", image: "/images/NEW%20CLIENTS%20LOGO/bcit_logo.webp" },
        { name: "Edify School", image: "/images/NEW%20CLIENTS%20LOGO/Edify%20Logo.jpg" },
        { name: "Hotel Sidh Vedantha", image: "/images/NEW%20CLIENTS%20LOGO/Hotel%20Sidh%20Vedantha%20logo.webp" },
        { name: "New Era High School", image: "/images/NEW%20CLIENTS%20LOGO/NEW%20ERA%20HIGH%20SCHOOL%20LOGO.png" },
        { name: "Patna Dental Clinic", image: "/images/NEW%20CLIENTS%20LOGO/Patna%20Dental%20Final%20Logo.png" },
        { name: "Medica Emergency", image: "/images/NEW%20CLIENTS%20LOGO/Medica%20Emergency%20logo.png" },
        { name: "Medica Hospital", image: "/images/NEW%20CLIENTS%20LOGO/Medica%20Logo%20for%20Social%20Media.png" },
        { name: "Satyadev Hospital", image: "/images/NEW%20CLIENTS%20LOGO/Satyadev%20Urology%20Logo.jpg" },
        { name: "Technosys", image: "/images/NEW%20CLIENTS%20LOGO/technosys-logo%20(1).png" },
        { name: "Weddings72 Planners", image: "/images/NEW%20CLIENTS%20LOGO/WEDDINGS72%20LOGO.png" },
        { name: "Abhayanand Super 30", image: "/images/NEW%20CLIENTS%20LOGO/abhayanand_logo-170x115.png" },
        { name: "Arvind Foundation", image: "/images/NEW%20CLIENTS%20LOGO/arvind%20foundation%20logo%20copy.png" },
        { name: "Sheodeni Sao College", image: "/images/NEW%20CLIENTS%20LOGO/SHEODENI%20SAO%20COLLEGE%20LOGO-01.png" },
        { name: "Unicare Hospital", image: "/images/NEW%20CLIENTS%20LOGO/Unicare%20logo.png" },
        { name: "Vedanta Hospital", image: "/images/NEW%20CLIENTS%20LOGO/vedantalogo.png" },
        { name: "Sita Interior", image: "/images/NEW%20CLIENTS%20LOGO/SITA-ARCH-LOGO-DKPorKRm.webp" },
        { name: "Tax Protect", image: "/images/NEW%20CLIENTS%20LOGO/Tax%20Protect%20Logo%20-%2009-June-2022.png" },
        { name: "Rapid House", image: "/images/NEW%20CLIENTS%20LOGO/rapid_logo.png" },
        { name: "ClickCharm", image: "/images/NEW%20CLIENTS%20LOGO/logo%20(3)%20-%20Copy.png" },
        { name: "Kiara", image: "/images/NEW%20CLIENTS%20LOGO/kiayra-removebg-preview.webp" },
        { name: "Natural Spa", image: "/images/NEW%20CLIENTS%20LOGO/NATURAL%20SPA.png" },
        { name: "Nirmal Inn", image: "/images/NEW%20CLIENTS%20LOGO/Nirmal%20Inn%20logo2.png" },
        { name: "Parkomico", image: "/images/NEW%20CLIENTS%20LOGO/Parkomiko.png" },
        { name: "Score High", image: "/images/NEW%20CLIENTS%20LOGO/SCORE%20HIGH%20LOGO.jpg" },
        { name: "K.P Sinha", image: "/images/NEW%20CLIENTS%20LOGO/K.P%20Sinha%20Logo.png" },
        { name: "MIA", image: "/images/NEW%20CLIENTS%20LOGO/MIA%20logo.png" },
        { name: "Krrish Fabricators", image: "/images/NEW%20CLIENTS%20LOGO/Krrish%20Fabricators%20Logo%20-%20Copy.png" },
      ],
    },
  },
];

export const portfolioGroup = { id: "portfolio", label: "Portfolio", description: "The /portfolio page.", sections };
