import type { Section } from "../home-sections";

const sections: Section[] = [
  {
    id: "hero",
    label: "Hero",
    description: "Headline and intro (the interactive simulator + phone stay in code).",
    ready: true,
    fields: [
      { name: "headingLine1", label: "Heading — line 1", type: "text", default: "SMS Gateways" },
      { name: "headingLine2", label: "Heading — line 2 (highlighted)", type: "text", default: "Built For Speed." },
      { name: "description", label: "Description", type: "textarea", default: "Experience our lightning-fast enterprise delivery engine. Compose a mock message below to test the routing visualizer and see it arrive instantly on the phone." },
      { name: "consoleTitle", label: "Console — title", type: "text", default: "Live Test Console" },
      { name: "consoleNote", label: "Console — note", type: "text", default: "No real charge" },
      { name: "senderLabel", label: "Console — sender label", type: "text", default: "Sender ID" },
      { name: "destLabel", label: "Console — destination label", type: "text", default: "Simulated Destination Number" },
      { name: "destValue", label: "Console — destination value", type: "text", default: "+91 99999 99999" },
      { name: "bodyLabel", label: "Console — body label", type: "text", default: "SMS Message Body" },
      { name: "sendLabel", label: "Console — send button", type: "text", default: "Send SMS Demo" },
      { name: "sendingLabel", label: "Console — sending state", type: "text", default: "Routing via Gateway..." },
      { name: "messagePlaceholder", label: "Console — message placeholder", type: "text", default: "Type your message..." },
      { name: "senderIdDefault", label: "Console — default sender ID", type: "text", default: "FILLIP" },
      { name: "messageDefault", label: "Console — default message", type: "textarea", default: "Your OTP for secure registration is 829104. Valid for 5 minutes. Do not share this code." },
      { name: "phoneDate", label: "Phone — date", type: "text", default: "Wednesday, July 1" },
      { name: "notifNow", label: "Phone — notification time", type: "text", default: "now" },
      { name: "deliveredNote", label: "Phone — delivered note", type: "text", default: "DELIVERED via VIP Route (1.8s)" },
    ],
  },
  {
    id: "features",
    label: "Features",
    description: "Heading, intro and the capability cards (icons/colours stay in code).",
    ready: true,
    fields: [
      { name: "headingLine1", label: "Heading — line 1", type: "text", default: "Communication Engineered" },
      { name: "headingLine2", label: "Heading — line 2 (highlighted)", type: "text", default: "For Perfect Delivery." },
      { name: "description", label: "Description", type: "textarea", default: "Our gateway is equipped with multiple operator tie-ups and direct router pipes, giving you low latencies and bulletproof delivery analytics." },
    ],
    list: {
      name: "items",
      label: "Feature cards",
      itemNoun: "feature",
      itemFields: [
        { name: "title", label: "Title", type: "text" },
        { name: "desc", label: "Description", type: "textarea" },
      ],
      default: [
        { title: "Transactional Alerts & OTPs", desc: "Deploy two-factor authentication codes, booking verifications, and invoice receipts in under 3 seconds." },
        { title: "Promotional Broadcasts", desc: "Draft marketing campaigns, schedule bulk product announcements, and distribute coupon codes instantly." },
        { title: "Developer REST APIs", desc: "Robust REST, HTTP, and SMPP endpoints that allow you to integrate SMS triggers into any codebase in 5 lines of code." },
        { title: "Intelligent Fallback Routing", desc: "Our smart system switches operator pipelines dynamically to avoid congestion and maintain 99.9% deliverability." },
      ],
    },
  },
  {
    id: "api",
    label: "API Integration",
    description: "Heading, intro and the capability list (the routing diagram stays in code).",
    ready: true,
    fields: [
      { name: "badge", label: "Badge", type: "text", default: "API Integration Solutions" },
      { name: "headingLine1", label: "Heading — line 1", type: "text", default: "Seamless SMS API" },
      { name: "headingLine2", label: "Heading — line 2 (highlighted)", type: "text", default: "For Your Applications." },
      { name: "description", label: "Description", type: "textarea", default: "We provide robust, secure, and developer-backed SMS APIs that plug directly into your web portals, checkouts, and custom databases." },
      { name: "leftTitle", label: "Left panel — title", type: "text", default: "Unified Messaging Gateway" },
      { name: "leftDescription", label: "Left panel — description", type: "textarea", default: "Connect your business logic to our delivery gateway. We offer ready-to-use SMS API endpoints tailored for immediate transaction notifications and customer alerts." },
      { name: "flowTitle", label: "Flow — heading", type: "text", default: "How our API Works" },
      { name: "flowSubtitle", label: "Flow — eyebrow", type: "text", default: "✦ SMS Transmission Architecture" },
      { name: "stepLabel", label: "Flow — step word", type: "text", default: "STEP" },
      { name: "flow1Title", label: "Flow step 1 — title", type: "text", default: "API Request Triggered" },
      { name: "flow1Desc", label: "Flow step 1 — description", type: "textarea", default: "Your platform sends an HTTP POST request to the API with recipient & body payload." },
      { name: "flow2Title", label: "Flow step 2 — title", type: "text", default: "Fillip Routing Engine" },
      { name: "flow2Desc", label: "Flow step 2 — description", type: "textarea", default: "Processes details, formats template validation, and forwards to carrier networks." },
      { name: "flow3Title", label: "Flow step 3 — title", type: "text", default: "Delivered Instantly" },
      { name: "flow3Desc", label: "Flow step 3 — description", type: "textarea", default: "The SMS reaches your user in < 2 seconds. A status report is returned via webhook." },
      { name: "footerLeft", label: "Flow footer — left", type: "text", default: "Security: TLS 1.3 / AES-256" },
      { name: "footerRight", label: "Flow footer — right", type: "text", default: "● Active API Endpoint" },
    ],
    list: {
      name: "items",
      label: "Capability rows",
      itemNoun: "capability",
      itemFields: [
        { name: "title", label: "Title", type: "text" },
        { name: "desc", label: "Description", type: "textarea" },
      ],
      default: [
        { title: "One-Time Password (OTP) Auth", desc: "Send instant 6-digit verifications for logins, signups, and financial transactions with priority delivery routing." },
        { title: "Automated System Alerts", desc: "Configure automated triggers for ticket bookings, order dispatch notices, billing receipts, and schedule reminders." },
        { title: "Real-Time Callback Webhooks", desc: "Receive instant delivery status reports (DLR), error codes, and latency checks routed directly back to your database." },
      ],
    },
  },
  {
    id: "pricing",
    label: "Pricing",
    description: "Heading, intro, included-features list and CTA (the slider/tier logic stays in code).",
    ready: true,
    fields: [
      { name: "headingLine1", label: "Heading — line 1", type: "text", default: "Paid Packages Built" },
      { name: "headingLine2", label: "Heading — line 2 (highlighted)", type: "text", default: "For Scale & Savings." },
      { name: "description", label: "Description", type: "textarea", default: "Drag the volume slider to see the carrier route specifications, support levels, and features dedicated for each tier." },
      { name: "includedTitle", label: "Included panel — title", type: "text", default: "What is included" },
      { name: "ctaLabel", label: "Button label", type: "text", default: "Get Started Now" },
      { name: "estimateLabel", label: "Slider — estimate label", type: "text", default: "Estimated Monthly SMS" },
      { name: "smsUnit", label: "Slider — unit", type: "text", default: "SMS" },
      { name: "routeTypeLabel", label: "Spec — route type label", type: "text", default: "Route Type" },
      { name: "setupTimeLabel", label: "Spec — setup time label", type: "text", default: "Setup Time" },
      { name: "supportLabel", label: "Spec — support label", type: "text", default: "Support Level" },
      { name: "featuresBadge", label: "Package — features badge", type: "text", default: "All-Inclusive Features" },
      { name: "mark1", label: "Slider mark 1", type: "text", default: "5k" },
      { name: "mark2", label: "Slider mark 2", type: "text", default: "100k" },
      { name: "mark3", label: "Slider mark 3", type: "text", default: "500k" },
      { name: "mark4", label: "Slider mark 4", type: "text", default: "1M+" },
      { name: "legend1", label: "Tier legend 1", type: "text", default: "● <25k: Starter Plan" },
      { name: "legend2", label: "Tier legend 2", type: "text", default: "● 25k-100k: Growth Plan" },
      { name: "legend3", label: "Tier legend 3", type: "text", default: "● 100k-500k: Corporate Plan" },
      { name: "legend4", label: "Tier legend 4", type: "text", default: "● 500k+: Enterprise SLA" },
      { name: "tier1RouteType", label: "Tier 1 (<25k) — route type", type: "text", default: "Standard Carrier Route" },
      { name: "tier1SetupTime", label: "Tier 1 (<25k) — setup time", type: "text", default: "Instant Activation" },
      { name: "tier1Support", label: "Tier 1 (<25k) — support", type: "text", default: "Standard Email Support" },
      { name: "tier1Badge", label: "Tier 1 (<25k) — badge", type: "text", default: "Starter Plan" },
      { name: "tier2RouteType", label: "Tier 2 (25k+) — route type", type: "text", default: "Standard Direct Route" },
      { name: "tier2SetupTime", label: "Tier 2 (25k+) — setup time", type: "text", default: "DLT Setup" },
      { name: "tier2Support", label: "Tier 2 (25k+) — support", type: "text", default: "Standard Email & Chat" },
      { name: "tier2Badge", label: "Tier 2 (25k+) — badge", type: "text", default: "Growth Plan" },
      { name: "tier3RouteType", label: "Tier 3 (100k+) — route type", type: "text", default: "Priority Carrier Route" },
      { name: "tier3SetupTime", label: "Tier 3 (100k+) — setup time", type: "text", default: "Priority DLT Setup" },
      { name: "tier3Support", label: "Tier 3 (100k+) — support", type: "text", default: "Priority Phone & Chat" },
      { name: "tier3Badge", label: "Tier 3 (100k+) — badge", type: "text", default: "Corporate Plan" },
      { name: "tier4RouteType", label: "Tier 4 (500k+) — route type", type: "text", default: "Dedicated Trunking" },
      { name: "tier4SetupTime", label: "Tier 4 (500k+) — setup time", type: "text", default: "Managed Custom Setup" },
      { name: "tier4Support", label: "Tier 4 (500k+) — support", type: "text", default: "24/7 Account Manager" },
      { name: "tier4Badge", label: "Tier 4 (500k+) — badge", type: "text", default: "Enterprise SLA" },
    ],
    list: {
      name: "included",
      label: "Included features",
      itemNoun: "feature",
      itemFields: [{ name: "text", label: "Feature", type: "text" }],
      default: [
        { text: "DLT Header / Sender ID Registration Support" },
        { text: "Unicode SMS Support (Multiple Languages)" },
        { text: "Real-Time Live Webhook Delivery Reports" },
        { text: "Direct Carrier Route with Smart Failover" },
        { text: "No Setup Fee & Credits Never Expire" },
        { text: "Standard REST APIs & Developer SDKs" },
      ],
    },
  },
  {
    id: "faq",
    label: "FAQs",
    description: "Heading and the question/answer list.",
    ready: true,
    fields: [
      { name: "badge", label: "Badge", type: "text", default: "Common Inquiries" },
      { name: "heading", label: "Heading", type: "text", default: "Frequently Asked Questions" },
    ],
    list: {
      name: "faqs",
      label: "Questions",
      itemNoun: "question",
      itemFields: [
        { name: "q", label: "Question", type: "text" },
        { name: "a", label: "Answer", type: "textarea" },
      ],
      default: [
        { q: "What is DLT registration and is it mandatory?", a: "Yes, in India, Distributed Ledger Technology (DLT) registration is mandatory as per TRAI regulations to combat spam. You must register your business entity, headers (sender IDs), and templates on an operator portal before sending messages. Our team provides complete assistance to get you approved." },
        { q: "What is the difference between Transactional and Promotional routes?", a: "Transactional SMS is used for critical alerts like OTPs and booking updates. They can be sent 24/7 and are delivered to all numbers (including DND). Promotional SMS is for marketing, discounts, and campaigns. They can only be sent between 9 AM and 9 PM and are not delivered to numbers registered on the DND registry." },
        { q: "How long does custom Sender ID (Header) approval take?", a: "Once DLT entity registration is complete, header (Sender ID) approvals typically take 24 to 48 hours on the operator DLT portal. Once approved there, it is active instantly on our gateway." },
        { q: "Do you support API integrations with webhooks?", a: "Absolutely. We offer high-performance REST APIs in multiple programming languages, along with live webhooks to receive real-time delivery status reports (DLR) directly back to your server databases." },
        { q: "How do I top up my SMS credits and do they expire?", a: "You can purchase SMS credits online via UPI, Credit Card, or Net Banking. Purchased credits do not expire and roll over indefinitely, allowing you to use them at your own pace." },
      ],
    },
  },
];

export const smsCommunicationGroup = {
  id: "sms-communication",
  label: "SMS Communication (Solution)",
  description: "The /solutions/sms-communication page.",
  sections,
};
