import type { Section } from "../home-sections";

const sections: Section[] = [
  {
    id: "hero",
    label: "Hero",
    description: "Headline, intro, buttons and the three stats (dashboard mock stays in code).",
    ready: true,
    fields: [
      { name: "badge", label: "Badge", type: "text", default: "Ticketing Platform Development Services" },
      { name: "heading", label: "Heading", type: "text", default: "Ticketing Platform Development Services" },
      { name: "description", label: "Description", type: "textarea", default: "Build secure, scalable and intelligent ticketing solutions for tourism, public attractions, events and organizations." },
      { name: "primaryCtaLabel", label: "Primary button", type: "text", default: "Discuss Your Platform" },
      { name: "secondaryCtaLabel", label: "Secondary button", type: "text", default: "View Sample Dashboard" },
      { name: "mockUrl", label: "Mock — browser URL", type: "text", default: "ticketing.fillip.dev" },
      { name: "mockBookingTag", label: "Mock — booking tag", type: "text", default: "Online Booking" },
      { name: "mockBookingTitle", label: "Mock — booking title", type: "text", default: "Reserve a visit" },
      { name: "mockDateLabel", label: "Mock — date label", type: "text", default: "Date" },
      { name: "mockDateValue", label: "Mock — date value", type: "text", default: "Sat, 21 Jun" },
      { name: "mockGuestsLabel", label: "Mock — guests label", type: "text", default: "Guests" },
      { name: "mockGuestsValue", label: "Mock — guests value", type: "text", default: "03" },
      { name: "mockCategoryLabel", label: "Mock — category label", type: "text", default: "Category" },
      { name: "mockCategoryValue", label: "Mock — category value", type: "text", default: "General" },
      { name: "mockSlotLabel", label: "Mock — slot label", type: "text", default: "Slot" },
      { name: "mockSlotValue", label: "Mock — slot value", type: "text", default: "10:30 AM" },
      { name: "mockTotalLabel", label: "Mock — total label", type: "text", default: "Total" },
      { name: "mockTotalValue", label: "Mock — total value", type: "text", default: "Rs 450" },
      { name: "mockPayLabel", label: "Mock — pay button", type: "text", default: "Pay and Confirm" },
      { name: "mockTicketLabel", label: "Mock — ticket label", type: "text", default: "Digital Ticket" },
      { name: "mockTicketCode", label: "Mock — ticket code", type: "text", default: "FT-39A11C" },
      { name: "mockTicketNote", label: "Mock — ticket note", type: "text", default: "Scan at entry gate to validate" },
      { name: "mockPosTag", label: "Mock — POS tag", type: "text", default: "Counter POS" },
      { name: "mockPosTitle", label: "Mock — POS title", type: "text", default: "Window 02 Live" },
      { name: "mockPosBadge", label: "Mock — POS badge", type: "text", default: "Open" },
      { name: "mockPosRow1Label", label: "Mock — POS row 1 label", type: "text", default: "Adult x 4" },
      { name: "mockPosRow1Value", label: "Mock — POS row 1 value", type: "text", default: "Rs 400" },
      { name: "mockPosRow2Label", label: "Mock — POS row 2 label", type: "text", default: "Child x 2" },
      { name: "mockPosRow2Value", label: "Mock — POS row 2 value", type: "text", default: "Rs 100" },
      { name: "mockPosRow3Label", label: "Mock — POS row 3 label", type: "text", default: "Add-on x 1" },
      { name: "mockPosRow3Value", label: "Mock — POS row 3 value", type: "text", default: "Rs 50" },
      { name: "mockPosIssueLabel", label: "Mock — POS issue label", type: "text", default: "Issue Ticket" },
      { name: "mockPosIssueValue", label: "Mock — POS issue value", type: "text", default: "Rs 550" },
      { name: "mockVisitorsLabel", label: "Mock — visitors label", type: "text", default: "Today Visitors" },
      { name: "mockVisitorsValue", label: "Mock — visitors value", type: "text", default: "3,284" },
      { name: "mockVisitorsDelta", label: "Mock — visitors delta", type: "text", default: "+18%" },
      { name: "mockVisitorsNote", label: "Mock — visitors note", type: "text", default: "Peak 11AM - 524/hr" },
      { name: "mockBadge1", label: "Mock — floating badge 1", type: "text", default: "QR Validated" },
      { name: "mockBadge2", label: "Mock — floating badge 2", type: "text", default: "Real-Time Reporting" },
    ],
    list: {
      name: "stats",
      label: "Stats",
      itemNoun: "stat",
      itemFields: [
        { name: "k", label: "Value", type: "text" },
        { name: "v", label: "Label", type: "text" },
      ],
      default: [
        { k: "Online", v: "Booking Flows" },
        { k: "QR", v: "Entry Validation" },
        { k: "Live", v: "Admin Reporting" },
      ],
    },
  },
  {
    id: "offer",
    label: "What We Offer",
    description: "Heading, intro, side panel labels and the solution cards.",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "What We Offer" },
      { name: "title", label: "Title", type: "text", default: "Our Ticketing Solutions" },
      { name: "description", label: "Description", type: "textarea", default: "Fillip Technologies builds complete ticketing platforms around your operations, not a generic template. Every module works together across online booking, counters, gates, finance and administration." },
      { name: "panelTitle", label: "Side panel — title", type: "text", default: "End-to-end platform" },
      { name: "panelSubtitle", label: "Side panel — subtitle", type: "text", default: "Built for live operational control" },
      { name: "decorImage", label: "Decorative image", type: "image", default: "/images/ticket-booking-What.png" },
      { name: "panelItem1", label: "Side panel — item 1", type: "text", default: "Slot Booking" },
      { name: "panelItem2", label: "Side panel — item 2", type: "text", default: "Payment Gateway Integration" },
      { name: "panelItem3", label: "Side panel — item 3", type: "text", default: "Reporting and Analytics" },
      { name: "panelItem4", label: "Side panel — item 4", type: "text", default: "Admin Dashboard" },
      { name: "panelItem5", label: "Side panel — item 5", type: "text", default: "Capacity Management" },
    ],
    list: {
      name: "solutions",
      label: "Solution cards",
      itemNoun: "solution",
      itemFields: [
        { name: "title", label: "Title", type: "text" },
        { name: "body", label: "Description", type: "textarea" },
      ],
      default: [
        { title: "Online Ticket Booking", body: "Responsive booking journeys with categories, visitor details, add-ons, secure payments and instant digital ticket delivery." },
        { title: "Counter Ticketing", body: "Fast operator screens for walk-in sales, receipt printing, payment modes, shift reports and synchronized inventory." },
        { title: "QR Based Entry Validation", body: "Signed QR codes, scan logs, duplicate-entry prevention and gate-level visibility for smooth visitor movement." },
        { title: "Visitor Management", body: "Structured visitor profiles, group bookings, category rules and role-based workflows for operations teams." },
      ],
    },
  },
  {
    id: "capabilities",
    label: "Key Capabilities",
    description: "Heading, intro and the three capability blocks.",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "Key Capabilities" },
      { name: "title", label: "Title", type: "text", default: "A connected platform for booking, operations and reporting." },
      { name: "description", label: "Description", type: "textarea", default: "We build the full product layer your organization needs: visitor experience, staff operations, gate validation, admin controls and business intelligence." },
    ],
    list: {
      name: "blocks",
      label: "Capability blocks",
      itemNoun: "block",
      itemFields: [
        { name: "title", label: "Title", type: "text" },
        { name: "lead", label: "Lead", type: "textarea" },
        { name: "body", label: "Body", type: "textarea" },
        { name: "points", label: "Point chips (comma-separated)", type: "text" },
      ],
      default: [
        { title: "Booking experiences that reduce friction", lead: "Visitors can choose tickets, dates, slots and payment methods without confusion.", body: "We design booking journeys for clarity, speed and trust, including responsive layouts, dynamic pricing, add-ons, refund logic and automated ticket delivery.", points: "Mobile-first booking, Category rules, Secure checkout, SMS and email delivery" },
        { title: "Unified counter and online operations", lead: "Offline ticket sales stay connected to the same inventory and reporting system.", body: "Counter teams get practical screens for fast sales, payment collection, receipt printing, shift close and supervisor review.", points: "Counter POS, Printer support, Shift reconciliation, Unified inventory" },
        { title: "Entry control and capacity intelligence", lead: "Every entry can be validated, tracked and reported in real time.", body: "Gate teams can scan QR tickets, prevent duplicate use, monitor capacity and keep operations moving during high-footfall periods.", points: "Signed QR codes, Duplicate prevention, Gate scan logs, Live capacity" },
      ],
    },
  },
  {
    id: "howitworks",
    label: "How It Works",
    description: "Heading, intro and the process steps.",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "How It Works" },
      { name: "title", label: "Title", type: "text", default: "From operational planning to a reliable live platform." },
      { name: "description", label: "Description", type: "textarea", default: "Our process is structured for organizations that need dependable technology, clear accountability and smooth handover to internal teams." },
      { name: "decorImage", label: "Decorative image", type: "image", default: "/images/How-we-work.png" },
    ],
    list: {
      name: "steps",
      label: "Steps",
      itemNoun: "step",
      itemFields: [
        { name: "t", label: "Title", type: "text" },
        { name: "d", label: "Description", type: "textarea" },
      ],
      default: [
        { t: "Discovery and Workflow Mapping", d: "We understand visitor journeys, ticket categories, permissions, pricing, approval paths and operational constraints." },
        { t: "UX and Platform Architecture", d: "We define booking screens, counter flows, admin roles, data models, integrations and reporting requirements." },
        { t: "Development and Integration", d: "We build the booking portal, counter POS, QR validation, dashboards, payment gateway and notification layer." },
        { t: "Testing and Launch", d: "We validate payments, load behavior, security, scan flows, reports and staff readiness before production rollout." },
        { t: "Support and Optimization", d: "We provide training, maintenance, monitoring and feature improvements as your operations evolve." },
      ],
    },
  },
  {
    id: "industries",
    label: "Industries",
    description: "Heading, intro and the industries grid (icons stay in code).",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "Industries We Serve" },
      { name: "title", label: "Title", type: "text", default: "Ticketing systems for venues, institutions and high-footfall experiences." },
      { name: "description", label: "Description", type: "textarea", default: "Our platforms support organizations where admission control, capacity, payments and visitor experience need to work together." },
      { name: "itemCaption", label: "Card caption", type: "text", default: "Booking - Validation - Reporting" },
    ],
    list: {
      name: "items",
      label: "Industries",
      itemNoun: "industry",
      itemFields: [{ name: "t", label: "Label", type: "text" }],
      default: [
        { t: "Tourism Attractions" }, { t: "Safari and Nature Parks" }, { t: "Museums" },
        { t: "Heritage Sites" }, { t: "Events and Exhibitions" }, { t: "Government Venues" },
        { t: "Theme Parks" }, { t: "Cultural Centers" }, { t: "Organizations" },
      ],
    },
  },
  {
    id: "whychoose",
    label: "Why Choose Us",
    description: "Heading, intro and the pillar cards (icons stay in code).",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "Why Choose Fillip Technologies" },
      { name: "title", label: "Title", type: "text", default: "Built for organizations that need reliable ticketing operations." },
      { name: "description", label: "Description", type: "textarea", default: "We combine product strategy, software engineering, UX design and operational support to deliver ticketing platforms your teams can trust every day." },
      { name: "decorImage", label: "Decorative image", type: "image", default: "/images/tckt-why.png" },
    ],
    list: {
      name: "pillars",
      label: "Pillars",
      itemNoun: "pillar",
      itemFields: [
        { name: "t", label: "Title", type: "text" },
        { name: "d", label: "Description", type: "textarea" },
      ],
      default: [
        { t: "Technology partner mindset", d: "We help shape the platform around your business goals, staff workflows and visitor expectations." },
        { t: "Scalable architecture", d: "Platforms are engineered for traffic spikes, high transaction volume and long-term feature growth." },
        { t: "Secure implementation", d: "Payment integrations, signed QR tickets, role-based access, audit trails and hardened APIs are planned from the start." },
        { t: "Custom workflows", d: "We model your ticket rules, slots, counters, capacity limits, approvals and reporting needs instead of forcing generic behavior." },
        { t: "Clean user experience", d: "Visitors, counter staff, gate teams and administrators get interfaces designed for speed and confidence." },
        { t: "Long-term support", d: "We stay involved after launch with monitoring, maintenance, training and ongoing platform improvements." },
      ],
    },
  },
  {
    id: "dashboard",
    label: "Dashboard Showcase",
    description: "Heading, intro and the feature list beside the dashboard image.",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "Dashboard Showcase" },
      { name: "title", label: "Title", type: "text", default: "A sample platform view built by Fillip Technologies." },
      { name: "description", label: "Description", type: "textarea", default: "This dashboard preview shows the type of operational control surface we can build for ticket sales, revenue, capacity and live entry management." },
      { name: "image", label: "Dashboard image", type: "image", default: "/images/analytics-dashboard.jpg" },
    ],
    list: {
      name: "items",
      label: "Feature list",
      itemNoun: "feature",
      itemFields: [{ name: "t", label: "Label", type: "text" }],
      default: [
        { t: "Ticket Sales" }, { t: "Revenue Reports" }, { t: "Visitor Analytics" },
        { t: "Capacity Monitoring" }, { t: "Entry Validation" }, { t: "Peak Visitor Tracking" },
      ],
    },
  },
  {
    id: "faq",
    label: "FAQs",
    description: "Heading and the question/answer list.",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "FAQ" },
      { name: "title", label: "Title", type: "text", default: "Questions organizations ask before building a ticketing platform." },
    ],
    list: {
      name: "faqs",
      label: "Questions",
      itemNoun: "question",
      itemFields: [
        { name: "q", label: "Question", type: "text" },
        { name: "a", label: "Answer", type: "textarea" },
      ],
      default: [
        { q: "Can Fillip Technologies build a custom ticketing platform for our organization?", a: "Yes. We design and develop custom ticketing platforms for organizations that need online booking, counter sales, QR validation, dashboards and operational workflows tailored to their needs." },
        { q: "Can the platform support both online and counter ticketing?", a: "Yes. We can build online booking and counter POS as part of one connected system, so inventory, reports and entry validation stay synchronized." },
        { q: "Do you integrate payment gateways?", a: "Yes. We integrate suitable payment gateways, configure transaction flows, support reconciliation needs and connect payment status with ticket generation." },
        { q: "Can we manage slots, capacity and visitor categories?", a: "Yes. The platform can include slot booking, capacity rules, visitor categories, pricing logic, add-ons and admin controls." },
        { q: "Do you provide support after launch?", a: "Yes. We can provide training, monitoring, maintenance, performance improvements and ongoing feature development after launch." },
      ],
    },
  },
];

export const ticketBookingGroup = {
  id: "ticket-booking",
  label: "Ticket Booking (Solution)",
  description: "The /solutions/ticket-booking page.",
  sections,
};
