import type { Section } from "../home-sections";

const sections: Section[] = [
  {
    id: "hero",
    label: "Hero",
    description: "Top banner headline, intro and buttons (the chat mock stays in code).",
    ready: true,
    fields: [
      { name: "badge", label: "Badge", type: "text", default: "WhatsApp Business Solutions" },
      { name: "headingLead", label: "Heading — before highlight", type: "text", default: "Never miss a" },
      { name: "headingHighlight", label: "Heading — highlighted word", type: "text", default: "lead" },
      { name: "headingTail", label: "Heading — after highlight", type: "text", default: "again." },
      { name: "subheading", label: "Sub-heading", type: "text", default: "Automate customer communication on WhatsApp." },
      { name: "description", label: "Description", type: "textarea", default: "Automate confirmations, notifications, follow-ups, reminders and customer engagement through intelligent WhatsApp workflows." },
      { name: "primaryCtaLabel", label: "Primary button", type: "text", default: "Book Consultation" },
      { name: "secondaryCtaLabel", label: "Secondary button", type: "text", default: "See How It Works" },
      { name: "pill1", label: "Trust pill 1", type: "text", default: "Meta-ready workflows" },
      { name: "pill2", label: "Trust pill 2", type: "text", default: "CRM integrations" },
      { name: "pill3", label: "Trust pill 3", type: "text", default: "Built for scale" },
      { name: "chatName", label: "Chat mock — name", type: "text", default: "Fillip Automation" },
      { name: "chatStatus", label: "Chat mock — status", type: "text", default: "online · replies instantly" },
      { name: "chatIncoming", label: "Chat mock — incoming message", type: "textarea", default: "Hi! I just submitted the enterprise enquiry form." },
      { name: "chatIncomingTime", label: "Chat mock — incoming time", type: "text", default: "10:42 AM" },
      { name: "chatReply", label: "Chat mock — reply message", type: "textarea", default: "Thanks, Priya. Your enquiry is confirmed. A solution specialist has been notified and will connect with you shortly." },
      { name: "chatReplyTime", label: "Chat mock — reply time", type: "text", default: "10:42 AM" },
      { name: "chatRoutedTitle", label: "Chat mock — routed card title", type: "text", default: "Lead routed to Enterprise Sales" },
      { name: "chatRoutedSubtitle", label: "Chat mock — routed card subtitle", type: "text", default: "Website form · High intent" },
      { name: "chatRoutedBadge", label: "Chat mock — routed badge", type: "text", default: "LIVE" },
      { name: "chatInputPlaceholder", label: "Chat mock — input placeholder", type: "text", default: "Type a message" },
      { name: "floatLabel1", label: "Floating label 1", type: "text", default: "24/7 Automation" },
      { name: "floatLabel2", label: "Floating label 2", type: "text", default: "Instant Notifications" },
      { name: "floatLabel3", label: "Floating label 3", type: "text", default: "Lead Conversion Boost" },
      { name: "floatLabel4", label: "Floating label 4", type: "text", default: "Smart Workflows" },
    ],
  },
  {
    id: "problem",
    label: "Problem (why leads are lost)",
    description: "Eyebrow, heading, intro and the problem steps.",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "The hidden revenue leak" },
      { name: "heading", label: "Heading", type: "text", default: "Why businesses lose leads." },
      { name: "description", label: "Description", type: "textarea", default: "Speed shapes intent. When an enquiry sits unanswered, interest decays and the next available business wins the conversation." },
      { name: "statusEarly", label: "Step caption — early steps", type: "text", default: "Intent waiting" },
      { name: "statusLate", label: "Step caption — later steps", type: "text", default: "Opportunity declining" },
    ],
    list: {
      name: "steps",
      label: "Problem steps",
      itemNoun: "step",
      itemFields: [{ name: "label", label: "Label", type: "text" }],
      default: [
        { label: "Customer fills enquiry form" },
        { label: "No immediate response" },
        { label: "Lead becomes cold" },
        { label: "Customer contacts competitor" },
        { label: "Business loses opportunity" },
      ],
    },
  },
  {
    id: "solution",
    label: "Solution (connected system)",
    description: "Eyebrow, heading, intro and the workflow steps.",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "One connected system" },
      { name: "heading", label: "Heading", type: "text", default: "Automate every customer interaction." },
      { name: "description", label: "Description", type: "textarea", default: "We design the complete journey from trigger to conversion, not merely the API connection behind it." },
      { name: "subFirst", label: "Step caption — first", type: "text", default: "A real business event" },
      { name: "subMiddle", label: "Step caption — middle", type: "text", default: "Orchestrated automatically" },
      { name: "subLast", label: "Step caption — last", type: "text", default: "Measured business outcome" },
    ],
    list: {
      name: "steps",
      label: "Workflow steps",
      itemNoun: "step",
      itemFields: [{ name: "label", label: "Label", type: "text" }],
      default: [
        { label: "Customer action" },
        { label: "WhatsApp automation" },
        { label: "Instant response" },
        { label: "Business notification" },
        { label: "Follow-up sequence" },
        { label: "Better conversion" },
      ],
    },
  },
  {
    id: "usecases",
    label: "Use cases",
    description: "Eyebrow, heading and the use-case rows (icons/chat bubbles stay in code).",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "Built around real moments" },
      { name: "heading", label: "Heading", type: "text", default: "Workflows customers actually experience." },
      { name: "tag", label: "Row tag", type: "text", default: "REAL USE CASE" },
      { name: "activeLabel", label: "Mock — active label", type: "text", default: "Automation active" },
      { name: "deliveredLabel", label: "Mock — delivered caption", type: "text", default: "Triggered and delivered automatically" },
      { name: "chip1", label: "Chip 1", type: "text", default: "Instant trigger" },
      { name: "chip2", label: "Chip 2", type: "text", default: "Personalized message" },
      { name: "chip3", label: "Chip 3", type: "text", default: "Team visibility" },
    ],
    list: {
      name: "items",
      label: "Use cases",
      itemNoun: "use case",
      itemFields: [
        { name: "number", label: "Number", type: "text" },
        { name: "title", label: "Title", type: "text" },
        { name: "copy", label: "Description", type: "textarea" },
        { name: "msg1", label: "Mock chat — bubble 1", type: "text" },
        { name: "msg2", label: "Mock chat — bubble 2", type: "text" },
      ],
      default: [
        { number: "01", title: "Website Form Automation", copy: "The moment a visitor submits your website form, they receive a personalized WhatsApp confirmation while your team gets a qualified lead alert.", msg1: "Thanks for your enquiry, Aisha.", msg2: "A specialist will contact you shortly." },
        { number: "02", title: "Appointment Booking", copy: "Confirm bookings instantly, send timely reminders and reduce no-shows without adding manual work for your operations team.", msg1: "Your appointment is confirmed.", msg2: "Reminder: Tomorrow at 11:30 AM" },
        { number: "03", title: "Order Updates", copy: "Keep customers informed from order confirmation to dispatch and delivery with automated, event-triggered status messages.", msg1: "Order #FT2048 is confirmed.", msg2: "Your order is out for delivery." },
        { number: "04", title: "Lead Notifications", copy: "Route high-intent leads to the right salesperson in real time, complete with source, requirement and customer contact details.", msg1: "New enterprise lead received.", msg2: "Assigned to Rahul · Sales Team" },
      ],
    },
  },
  {
    id: "difference",
    label: "The Fillip difference",
    description: "Eyebrow, heading, intro, the two comparison column headers and their rows.",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "The Fillip difference" },
      { name: "heading", label: "Heading", type: "text", default: "More than just WhatsApp API access." },
      { name: "description", label: "Description", type: "textarea", default: "An API sends messages. A well-designed automation system moves your business forward." },
      { name: "leftTitle", label: "Left column — label", type: "text", default: "Typical API provider" },
      { name: "leftHeading", label: "Left column — heading", type: "text", default: "You receive the plumbing." },
      { name: "rightTitle", label: "Right column — label", type: "text", default: "Fillip Technologies" },
      { name: "rightHeading", label: "Right column — heading", type: "text", default: "You receive the complete system." },
    ],
    list: {
      name: "items",
      label: "Comparison rows",
      itemNoun: "row",
      itemFields: [
        { name: "label", label: "Text", type: "text" },
        { name: "side", label: "Side (left or right)", type: "text" },
      ],
      default: [
        { label: "API access only", side: "left" },
        { label: "Complex setup", side: "left" },
        { label: "Limited support", side: "left" },
        { label: "Generic integrations", side: "left" },
        { label: "End-to-end setup", side: "right" },
        { label: "Business workflow design", side: "right" },
        { label: "Website integration", side: "right" },
        { label: "CRM integration", side: "right" },
        { label: "Custom automations", side: "right" },
        { label: "Dedicated support", side: "right" },
        { label: "Ongoing optimization", side: "right" },
      ],
    },
  },
  {
    id: "showcase",
    label: "Automation showcase",
    description: "Eyebrow, heading, engine label and the input/output signal rows.",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "Automation architecture" },
      { name: "heading", label: "Heading", type: "text", default: "Every signal. One intelligent engine." },
      { name: "engineTitle", label: "Engine label", type: "text", default: "WhatsApp Automation Engine" },
      { name: "engineSubtitle", label: "Engine sub-label", type: "text", default: "Logic · Routing · Personalization" },
    ],
    list: {
      name: "signals",
      label: "Signal rows",
      itemNoun: "signal",
      itemFields: [
        { name: "label", label: "Text", type: "text" },
        { name: "side", label: "Side (input or output)", type: "text" },
      ],
      default: [
        { label: "Website Form", side: "input" },
        { label: "Contact Form", side: "input" },
        { label: "Order Placement", side: "input" },
        { label: "Appointment Booking", side: "input" },
        { label: "Lead Capture", side: "input" },
        { label: "CRM Events", side: "input" },
        { label: "Customer Confirmation", side: "output" },
        { label: "Admin Notification", side: "output" },
        { label: "Follow-Up Message", side: "output" },
        { label: "Reminder Message", side: "output" },
        { label: "Sales Alert", side: "output" },
      ],
    },
  },
  {
    id: "industries",
    label: "Industries",
    description: "Eyebrow, heading and the industries grid (icons stay in code).",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "Industries we serve" },
      { name: "heading", label: "Heading", type: "text", default: "One engine. Different business moments." },
    ],
    list: {
      name: "industries",
      label: "Industries",
      itemNoun: "industry",
      itemFields: [{ name: "label", label: "Label", type: "text" }],
      default: [
        { label: "Education" }, { label: "Healthcare" }, { label: "Real Estate" },
        { label: "Travel" }, { label: "Restaurants" }, { label: "E-Commerce" },
        { label: "Training Institutes" }, { label: "Service Businesses" }, { label: "Agencies" },
      ],
    },
  },
  {
    id: "whyus",
    label: "Why Fillip Technologies",
    description: "Eyebrow, heading, intro and the reasons list.",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "Why Fillip Technologies" },
      { name: "heading", label: "Heading", type: "text", default: "Automation grounded in real business operations." },
      { name: "description", label: "Description", type: "textarea", default: "We combine product thinking, integration engineering and ongoing optimization to build workflows that stay useful as your business evolves." },
    ],
    list: {
      name: "items",
      label: "Reasons",
      itemNoun: "reason",
      itemFields: [
        { name: "number", label: "Number", type: "text" },
        { name: "title", label: "Title", type: "text" },
        { name: "copy", label: "Description", type: "textarea" },
      ],
      default: [
        { number: "01", title: "Real Business Automation Experience", copy: "Workflows designed around response time, team ownership and measurable outcomes." },
        { number: "02", title: "Custom Workflow Development", copy: "Logic tailored to your customer journey, policies and internal operations." },
        { number: "03", title: "Scalable Architecture", copy: "A dependable foundation that can expand across teams, locations and use cases." },
        { number: "04", title: "Fast Deployment", copy: "Focused delivery with clear milestones, integrations and production readiness." },
        { number: "05", title: "Dedicated Support", copy: "A team that stays involved after launch, not a dashboard and documentation handoff." },
        { number: "06", title: "Future Enhancements", copy: "Continuous refinement as customer behavior and business priorities change." },
      ],
    },
  },
  {
    id: "results",
    label: "Results (metrics)",
    description: "Eyebrow, heading, intro and the metric figures.",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "Designed for outcomes" },
      { name: "heading", label: "Heading", type: "text", default: "Communication that keeps moving." },
      { name: "description", label: "Description", type: "textarea", default: "Illustrative performance goals for a properly implemented automation ecosystem." },
    ],
    list: {
      name: "metrics",
      label: "Metrics",
      itemNoun: "metric",
      itemFields: [
        { name: "value", label: "Value", type: "text" },
        { name: "suffix", label: "Suffix", type: "text" },
        { name: "label", label: "Label", type: "text" },
      ],
      default: [
        { value: "60", suffix: "%", label: "Faster response time" },
        { value: "3", suffix: "x", label: "Better lead engagement" },
        { value: "24", suffix: "/7", label: "Automated communication" },
        { value: "100", suffix: "%", label: "Instant notifications" },
      ],
    },
  },
  {
    id: "cta",
    label: "Closing CTA",
    description: "The final call-to-action band.",
    ready: true,
    fields: [
      { name: "eyebrow", label: "Eyebrow", type: "text", default: "Start a conversation" },
      { name: "heading", label: "Heading", type: "text", default: "Ready to automate customer communication?" },
      { name: "description", label: "Description", type: "textarea", default: "Whether you need lead automation, enquiry workflows, customer notifications or complete WhatsApp business automation, Fillip Technologies can help you build a scalable communication ecosystem." },
      { name: "primaryCtaLabel", label: "Primary button", type: "text", default: "Schedule Consultation" },
      { name: "secondaryCtaLabel", label: "Secondary button", type: "text", default: "Contact Us" },
    ],
  },
];

export const whatsappBusinessGroup = {
  id: "whatsapp-business",
  label: "WhatsApp Business (Solution)",
  description: "The /solutions/whatsapp-business page.",
  sections,
};
