import {
  BarChart3,
  Boxes,
  BriefcaseBusiness,
  CheckCircle2,
  Clock3,
  Cloud,
  CreditCard,
  KeyRound,
  Layers3,
  Lock,
  Package,
  RefreshCw,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Store,
  TrendingUp,
  Truck,
  UserRound,
  Users,
  Wallet,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import type { MobileAppIconName } from "@/data/mobile-app-development";

export const mobileAppIcons: Record<MobileAppIconName, LucideIcon> = {
  BarChart3,
  Boxes,
  BriefcaseBusiness,
  CheckCircle2,
  Clock3,
  Cloud,
  CreditCard,
  KeyRound,
  Layers3,
  Lock,
  Package,
  RefreshCw,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Store,
  TrendingUp,
  Truck,
  UserRound,
  Users,
  Wallet,
  Workflow,
};
